name:                   generate-nixpkgs-haskell-package-list
version:                "0"
synopsis:               List Haskell packages in Nixpkgs for upload to Hackage.
description:            Generate the list of Haskell packages in Nixpkgs suitable for upload to Hackage.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
license-file:           LICENSE
github:                 peti/package-list
category:               Distribution
tested-with:            GHC > 7.6 && < 8.3

ghc-options:            -Wall

dependencies:
  - base < 5
  - Cabal >= 1.22.2
  - containers
  - language-nix
  - hackage-db >= 2
  - pretty
  - process
  - nix-paths

executables:
  generate-nixpkgs-haskell-package-list:
    main:               Main.hs
    source-dirs:        src
