name:                   generate-nixpkgs-haskell-package-list
version:                "20160608"
synopsis:               Generate the list of Haskell packages in Nixpkgs suitable for upload to Hackage.
description:            Generate the list of Haskell packages in Nixpkgs suitable for upload to Hackage.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 peti/package-list
category:               Distribution

ghc-options:            -Wall

dependencies:
  - base < 5
  - Cabal >= 1.22.2
  - containers
  - language-nix
  - hackage-db
  - pretty
  - process
  - nix-paths

executables:
  generate-nixpkgs-haskell-package-list:
    main:               Main.hs
    source-dirs:        src
